Vagrant.configure("2") do |config|
  config.vm.box = "assistive-webdriver/win10-chromium-nvda"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.name = "win10-chromium-nvda"
  end
end
