name: ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --frozen-lockfile
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: yarn ci && yarn scripts:test
      - uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          flags: unit
      - uses: codecov/codecov-action@v3
        with:
          file: coverage-e2e/lcov.info
          flags: e2e
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports
        if: ${{ always() }}
  sauce-labs:
    runs-on: ubuntu-latest
    name: Sauce Labs
    steps:
      - uses: actions/checkout@v3
      - uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: ng-bootstrap-${{ github.run_id }}
      - run: yarn saucelabs
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: sauce-connect-log
          path: ${{ env.SAUCE_CONNECT_DIR_IN_HOST }}/sauce-connect.log
