name: ci

on:
  push:
    branches:
      - master
      - '[0-9]+_[0-9]+_x'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn --frozen-lockfile --immutable
      - run: yarn playwright install-deps
      - run: yarn playwright install
      - run: yarn ci && yarn scripts:test
      - uses: codecov/codecov-action@v4
        with:
          file: coverage/lcov.info
          flags: unit
      - uses: codecov/codecov-action@v4
        with:
          file: coverage-e2e/lcov.info
          flags: e2e
      - uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports
        if: ${{ always() }}
